services:
  database:
    image: 'postgres:15.2'
    container_name: database
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  app:
    container_name: app
    build: ./
    depends_on: [ database ]