services:
  database:
    image: 'postgres:15.2'
    container_name: database
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  app:
    image: 'bellory/library-app'
    container_name: app
    build: ./
    depends_on: [ database ]
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/test
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test